name: 👑 CI

# This workflow updates the .pyi stub files for documentation and interactive use.

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-ci
  cancel-in-progress: true

jobs:
  ubuntu:
    name: 🐧 Ubuntu
    uses: ./.github/workflows/ubuntu.yml

  save_pr_number:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt
          retention-days: 1
